# Viral Metagenomics Pipeline for Nanopore Sequencing Data
#=======================================

## Description:
This pipeline performs viral metagenomic analysis from Nanopore sequencing reads obtained from clinical samples.

## Workflow:
 1. Create Conda environments
 2. Raw read quality control
 3. Adapter trimming and read filtering
 4. Kraken2 database setup
 5. Taxonomic classification with Kraken2
 6. Interactive visualization with Krona

---

In [1]:
!pip install --upgrade --force-reinstall zstandard
!pip install -q condacolab

import condacolab
condacolab.install()

!sed -i '/cudatoolkit/d' /usr/local/conda-meta/pinned
!sed -i '/python/d' /usr/local/conda-meta/pinned

!mamba install -c conda-forge curl --quiet

Collecting zstandard
  Using cached zstandard-0.25.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Using cached zstandard-0.25.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.6 MB)
Installing collected packages: zstandard
  Attempting uninstall: zstandard
    Found existing installation: zstandard 0.25.0
    Uninstalling zstandard-0.25.0:
      Successfully uninstalled zstandard-0.25.0
Successfully installed zstandard-0.25.0
✨🍰✨ Everything looks OK!

# 1. Create conda environments

In [2]:
# Instala a ferramenta via PyPI
!pip install NanoFilt
!NanoFilt -v

Collecting NanoFilt
  Downloading NanoFilt-2.8.0.tar.gz (7.4 kB)
  Preparing metadata (setup.py) ... done
Collecting biopython (from NanoFilt)
  Downloading biopython-1.87-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting pandas>=0.22.0 (from NanoFilt)
  Downloading pandas-3.0.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas>=0.22.0->NanoFilt)
  Downloading numpy-2.4.6-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas>=0.22.0->NanoFilt)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas>=0.22.0->NanoFilt)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading pandas-3.0.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 101.1 MB/s eta 0:00:00
Downloading biopython-1.87-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 109.3 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 125.7 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: NanoFilt
  Building wheel for NanoFilt (setup.py) ... done
  Created wheel for NanoFilt: filename=NanoFilt-2.8.0-py3-none-any.whl size=8776 sha256=fe4ad7fcd7b0231e77116f9c1b4b1e3db2b35a0dfcea6772e4abb438f67fe31c
  Stored in directory: /root/.cache/pip/wheels/53/f3/c9/126ce1c746762c3454032c9e59ce8bc10290e78a1ab8dae8cc
Successfully built NanoFilt
Installing collected packages: six, numpy, python-dateutil, biopython, pandas, NanoFilt
Successfully installed NanoFilt-2.8.0 biopython-1.87 numpy-2.4.6 pandas-3.0.3 python-dateutil-2.9.0.post0 six-1.17.0

NanoFilt 2.8.0

In [2]:
!mamba create -y -n nanopore_qc -c bioconda -c conda-forge nanoplot porechop nanofilt --quiet

!mamba create -y -n kraken_krona -c bioconda -c conda-forge kraken2 krona --quiet

!mamba install -y -c bioconda sra-tools --quiet

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working...
Krona installed.  You still need to manually update the taxonomy
databases before Krona can generate taxonomic reports.  The update
script is ktUpdateTaxonomy.sh.  The default location for storing
taxonomic databases is /usr/local/envs/kraken_krona/opt/krona/taxonomy

If you would like the taxonomic data stored elsewhere, simply replace
this directory with a symlink.  For example:

rm -rf /usr/local/envs/kraken_krona/opt/krona/taxonomy
mkdir /path/on/big/disk/taxonomy
ln -s /path/on/big/disk/taxonomy /usr/local/envs/kraken_krona/opt/krona/taxonomy
ktUpdateTaxonomy.sh


done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

# 2. Create directory structure and FASTQ file

In [3]:
# Directory
!mkdir -p analysis/{input,fastqc_pretrim,trimmed,fastqc_posttrim,kraken,krona}

# Download FASTQ file to input directory
!fasterq-dump ERR14817851
!gzip ERR14817851.fastq
!mv /content/ERR14817851.fastq.gz analysis/input/

spots read      : 117,928
reads read      : 117,928
reads written   : 117,928

# 3. Initial quality control with NanoPlot

In [4]:
# !mamba activate nanopore_qc
!mamba run -n nanopore_qc NanoPlot \
    --fastq analysis/input/ERR14817851.fastq.gz \
    -o analysis/fastqc_pretrim \
    -t 2

# Download
from google.colab import files
files.download("./analysis/fastqc_pretrim/NanoPlot-report.html")

# Open Nanoplot report
from IPython.display import HTML
with open("./analysis/fastqc_pretrim/NanoPlot-report.html", "r") as f:
    html = f.read()
HTML(html)

# 4. Adapter trimming and read filtering

In [5]:
# Running adapter trimming with Porechop
!mamba run -n nanopore_qc porechop \
    -i analysis/input/ERR14817851.fastq.gz \
    --threads 3 \
    -o analysis/trimmed/reads_trimmed.fastq.gz

Loading reads
analysis/input/ERR14817851.fastq.gz
117,928 reads loaded


Looking for known adapter sets

0 / 10,000 (0.0%)
10 / 10,000 (0.1%)
20 / 10,000 (0.2%)
30 / 10,000 (0.3%)
40 / 10,000 (0.4%)
50 / 10,000 (0.5%)
60 / 10,000 (0.6%)
70 / 10,000 (0.7%)
80 / 10,000 (0.8%)
90 / 10,000 (0.9%)
100 / 10,000 (1.0%)
110 / 10,000 (1.1%)
120 / 10,000 (1.2%)
130 / 10,000 (1.3%)
140 / 10,000 (1.4%)
150 / 10,000 (1.5%)
160 / 10,000 (1.6%)
170 / 10,000 (1.7%)
180 / 10,000 (1.8%)
190 / 10,000 (1.9%)
200 / 10,000 (2.0%)
210 / 10,000 (2.1%)
220 / 10,000 (2.2%)
230 / 10,000 (2.3%)
240 / 10,000 (2.4%)
250 / 10,000 (2.5%)
260 / 10,000 (2.6%)
270 / 10,000 (2.7%)
280 / 10,000 (2.8%)
290 / 10,000 (2.9%)
300 / 10,000 (3.0%)
310 / 10,000 (3.1%)
320 / 10,000 (3.2%)
330 / 10,000 (3.3%)
340 / 10,000 (3.4%)
350 / 10,000 (3.5%)
360 / 10,000 (3.6%)
370 / 10,000 (3.7%)
380 / 10,000 (3.8%)
390 / 10,000 (3.9%)
400 / 10,000 (4.0%)
410 / 10,000 (4.1%)
420 / 10,000 (4.2%)
430 / 10,000 (4.3%)
440 / 10,000 (4.4%)
450 / 10,000 (4.5%)
460 / 10,000 (4.6%)
470 / 10,000 (4.7%)
480 / 10,000 (4.8%)
490 / 10,000 (4.9%)
500 / 10,000 (5.0%)
510 / 10,000 (5.1%)
520 / 10,000 (5.2%)
530 / 10,000 (5.3%)
540 / 10,000 (5.4%)
550 / 10,000 (5.5%)
560 / 10,000 (5.6%)
570 / 10,000 (5.7%)
580 / 10,000 (5.8%)
590 / 10,000 (5.9%)
600 / 10,000 (6.0%)
610 / 10,000 (6.1%)
620 / 10,000 (6.2%)
630 / 10,000 (6.3%)
640 / 10,000 (6.4%)
650 / 10,000 (6.5%)
660 / 10,000 (6.6%)
670 / 10,000 (6.7%)
680 / 10,000 (6.8%)
690 / 10,000 (6.9%)
700 / 10,000 (7.0%)
710 / 10,000 (7.1%)
720 / 10,000 (7.2%)
730 / 10,000 (7.3%)
740 / 10,000 (7.4%)
750 / 10,000 (7.5%)
760 / 10,000 (7.6%)
770 / 10,000 (7.7%)
780 / 10,000 (7.8%)
790 / 10,000 (7.9%)
800 / 10,000 (8.0%)
810 / 10,000 (8.1%)
820 / 10,000 (8.2%)
830 / 10,000 (8.3%)
840 / 10,000 (8.4%)
850 / 10,000 (8.5%)
860 / 10,000 (8.6%)
870 / 10,000 (8.7%)
880 / 10,000 (8.8%)
890 / 10,000 (8.9%)
900 / 10,000 (9.0%)
910 / 10,000 (9.1%)
920 / 10,000 (9.2%)
930 / 10,000 (9.3%)
940 / 10,000 (9.4%)
950 / 10,000 (9.5%)
960 / 10,000 (9.6%)
970 / 10,000 (9.7%)
980 / 10,000 (9.8%)
990 / 10,000 (9.9%)
1,000 / 10,000 (10.0%)
1,010 / 10,000 (10.1%)
1,020 / 10,000 (10.2%)
1,030 / 10,000 (10.3%)
1,040 / 10,000 (10.4%)
1,050 / 10,000 (10.5%)
1,060 / 10,000 (10.6%)
1,070 / 10,000 (10.7%)
1,080 / 10,000 (10.8%)
1,090 / 10,000 (10.9%)
1,100 / 10,000 (11.0%)
1,110 / 10,000 (11.1%)
1,120 / 10,000 (11.2%)
1,130 / 10,000 (11.3%)
1,140 / 10,000 (11.4%)
1,150 / 10,000 (11.5%)
1,160 / 10,000 (11.6%)
1,170 / 10,000 (11.7%)
1,180 / 10,000 (11.8%)
1,190 / 10,000 (11.9%)
1,200 / 10,000 (12.0%)
1,210 / 10,000 (12.1%)
1,220 / 10,000 (12.2%)
1,230 / 10,000 (12.3%)
1,240 / 10,000 (12.4%)
1,250 / 10,000 (12.5%)
1,260 / 10,000 (12.6%)
1,270 / 10,000 (12.7%)
1,280 / 10,000 (12.8%)
1,290 / 10,000 (12.9%)
1,300 / 10,000 (13.0%)
1,310 / 10,000 (13.1%)
1,320 / 10,000 (13.2%)
1,330 / 10,000 (13.3%)
1,340 / 10,000 (13.4%)
1,350 / 10,000 (13.5%)
1,360 / 10,000 (13.6%)
1,370 / 10,000 (13.7%)
1,380 / 10,000 (13.8%)
1,390 / 10,000 (13.9%)
1,400 / 10,000 (14.0%)
1,410 / 10,000 (14.1%)
1,420 / 10,000 (14.2%)
1,430 / 10,000 (14.3%)
1,440 / 10,000 (14.4%)
1,450 / 10,000 (14.5%)
1,460 / 10,000 (14.6%)
1,470 / 10,000 (14.7%)
1,480 / 10,000 (14.8%)
1,490 / 10,000 (14.9%)
1,500 / 10,000 (15.0%)
1,510 / 10,000 (15.1%)
1,520 / 10,000 (15.2%)
1,530 / 10,000 (15.3%)
1,540 / 10,000 (15.4%)
1,550 / 10,000 (15.5%)
1,560 / 10,000 (15.6%)
1,570 / 10,000 (15.7%)
1,580 / 10,000 (15.8%)
1,590 / 10,000 (15.9%)
1,600 / 10,000 (16.0%)
1,610 / 10,000 (16.1%)
1,620 / 10,000 (16.2%)
1,630 / 10,000 (16.3%)
1,640 / 10,000 (16.4%)
1,650 / 10,000 (16.5%)
1,660 / 10,000 (16.6%)
1,670 / 10,000 (16.7%)
1,680 / 10,000 (16.8%)
1,690 / 10,000 (16.9%)
1,700 / 10,000 (17.0%)
1,710 / 10,000 (17.1%)
1,720 / 10,000 (17.2%)
1,730 / 10,000 (17.3%)
1,740 / 10,000 (17.4%)
1,750 / 10,000 (17.5%)
1,760 / 10,000 (17.6%)
1,770 / 10,000 (17.7%)
1,780 / 10,000 (17.8%)
1,790 / 10,000 (17.9%)
1,800 / 10,000 (18.0%)
1,810 / 10,000 (18.1%)
1,820 / 10,000 (18.2%)
1,830 / 10,000 (18.3%)
1,840 / 10,000 (18.4%)
1,850 / 10,000 (18.5%)
1,860 / 10,000 (18.6%)
1,870 / 10,000 (18.7%)
1,880 / 10,000 (18.8%)
1,890 / 10,000 (18.9%)
1,900 / 10,000 (19.0%)
1,910 / 10,000 (19.1%)
1,920 / 10,000 (19.2%)
1,930 / 10,000 (19.3%)
1,940 / 10,000 (19.4%)
1,950 / 10,000 (19.5%)
1,960 / 10,000 (19.6%)
1,970 / 10,000 (19.7%)
1,980 / 10,000 (19.8%)
1,990 / 10,000 (19.9%)
2,000 / 10,000 (20.0%)
2,010 / 10,000 (20.1%)
2,020 / 10,000 (20.2%)
2,030 / 10,000 (20.3%)
2,040 / 10,000 (20.4%)
2,050 / 10,000 (20.5%)
2,060 / 10,000 (20.6%)
2,070 / 10,000 (20.7%)
2,080 / 10,000 (20.8%)
2,090 / 10,000 (20.9%)
2,100 / 10,000 (21.0%)
2,110 / 10,000 (21.1%)
2,120 / 10,000 (21.2%)
2,130 / 10,000 (21.3%)
2,140 / 10,000 (21.4%)
2,150 / 10,000 (21.5%)
2,160 / 10,000 (21.6%)
2,170 / 10,000 (21.7%)
2,180 / 10,000 (21.8%)
2,190 / 10,000 (21.9%)
2,200 / 10,000 (22.0%)
2,210 / 10,000 (22.1%)
2,220 / 10,000 (22.2%)
2,230 / 10,000 (22.3%)
2,240 / 10,000 (22.4%)
2,250 / 10,000 (22.5%)
2,260 / 10,000 (22.6%)
2,270 / 10,000 (22.7%)
2,280 / 10,000 (22.8%)
2,290 / 10,000 (22.9%)
2,300 / 10,000 (23.0%)
2,310 / 10,000 (23.1%)
2,320 / 10,000 (23.2%)
2,330 / 10,000 (23.3%)
2,340 / 10,000 (23.4%)
2,350 / 10,000 (23.5%)
2,360 / 10,000 (23.6%)
2,370 / 10,000 (23.7%)
2,380 / 10,000 (23.8%)
2,390 / 10,000 (23.9%)
2,400 / 10,000 (24.0%)
2,410 / 10,000 (24.1%)
2,420 / 10,000 (24.2%)
2,430 / 10,000 (24.3%)
2,440 / 10,000 (24.4%)
2,450 / 10,000 (24.5%)
2,460 / 10,000 (24.6%)
2,470 / 10,000 (24.7%)
2,480 / 10,000 (24.8%)
2,490 / 10,000 (24.9%)
2,500 / 10,000 (25.0%)
2,510 / 10,000 (25.1%)
2,520 / 10,000 (25.2%)
2,530 / 10,000 (25.3%)
2,540 / 10,000 (25.4%)
2,550 / 10,000 (25.5%)
2,560 / 10,000 (25.6%)
2,570 / 10,000 (25.7%)
2,580 / 10,000 (25.8%)
2,590 / 10,000 (25.9%)
2,600 / 10,000 (26.0%)
2,610 / 10,000 (26.1%)
2,620 / 10,000 (26.2%)
2,630 / 10,000 (26.3%)
2,640 / 10,000 (26.4%)
2,650 / 10,000 (26.5%)
2,660 / 10,000 (26.6%)
2,670 / 10,000 (26.7%)
2,680 / 10,000 (26.8%)
2,690 / 10,000 (26.9%)
2,700 / 10,000 (27.0%)
2,710 / 10,000 (27.1%)
2,720 / 10,000 (27.2%)
2,730 / 10,000 (27.3%)
2,740 / 10,000 (27.4%)
2,750 / 10,000 (27.5%)
2,760 / 10,000 (27.6%)
2,770 / 10,000 (27.7%)
2,780 / 10,000 (27.8%)
2,790 / 10,000 (27.9%)
2,800 / 10,000 (28.0%)
2,810 / 10,000 (28.1%)
2,820 / 10,000 (28.2%)
2,830 / 10,000 (28.3%)
2,840 / 10,000 (28.4%)
2,850 / 10,000 (28.5%)
2,860 / 10,000 (28.6%)
2,870 / 10,000 (28.7%)
2,880 / 10,000 (28.8%)
2,890 / 10,000 (28.9%)
2,900 / 10,000 (29.0%)
2,910 / 10,000 (29.1%)
2,920 / 10,000 (29.2%)
2,930 / 10,000 (29.3%)
2,940 / 10,000 (29.4%)
2,950 / 10,000 (29.5%)
2,960 / 10,000 (29.6%)
2,970 / 10,000 (29.7%)
2,980 / 10,000 (29.8%)
2,990 / 10,000 (29.9%)
3,000 / 10,000 (30.0%)
3,010 / 10,000 (30.1%)
3,020 / 10,000 (30.2%)
3,030 / 10,000 (30.3%)
3,040 / 10,000 (30.4%)
3,050 / 10,000 (30.5%)
3,060 / 10,000 (30.6%)
3,070 / 10,000 (30.7%)
3,080 / 10,000 (30.8%)
3,090 / 10,000 (30.9%)
3,100 / 10,000 (31.0%)
3,110 / 10,000 (31.1%)
3,120 / 10,000 (31.2%)
3,130 / 10,000 (31.3%)
3,140 / 10,000 (31.4%)
3,150 / 10,000 (31.5%)
3,160 / 10,000 (31.6%)
3,170 / 10,000 (31.7%)
3,180 / 10,000 (31.8%)
3,190 / 10,000 (31.9%)
3,200 / 10,000 (32.0%)
3,210 / 10,000 (32.1%)
3,220 / 10,000 (32.2%)
3,230 / 10,000 (32.3%)
3,240 / 10,000 (32.4%)
3,250 / 10,000 (32.5%)
3,260 / 10,000 (32.6%)
3,270 / 10,000 (32.7%)
3,280 / 10,000 (32.8%)
3,290 / 10,000 (32.9%)
3,300 / 10,000 (33.0%)
3,310 / 10,000 (33.1%)
3,320 / 10,000 (33.2%)
3,330 / 10,000 (33.3%)
3,340 / 10,000 (33.4%)
3,350 / 10,000 (33.5%)
3,360 / 10,000 (33.6%)
3,370 / 10,000 (33.7%)
3,380 / 10,000 (33.8%)
3,390 / 10,000 (33.9%)
3,400 / 10,000 (34.0%)
3,410 / 10,000 (34.1%)
3,420 / 10,000 (34.2%)
3,430 / 10,000 (34.3%)
3,440 / 10,000 (34.4%)
3,450 / 10,000 (34.5%)
3,460 / 10,000 (34.6%)
3,470 / 10,000 (34.7%)
3,480 / 10,000 (34.8%)
3,490 / 10,000 (34.9%)
3,500 / 10,000 (35.0%)
3,510 / 10,000 (35.1%)
3,520 / 10,000 (35.2%)
3,530 / 10,000 (35.3%)
3,540 / 10,000 (35.4%)
3,550 / 10,000 (35.5%)
3,560 / 10,000 (35.6%)
3,570 / 10,000 (35.7%)
3,580 / 10,000 (35.8%)
3,590 / 10,000 (35.9%)
3,600 / 10,000 (36.0%)
3,610 / 10,000 (36.1%)
3,620 / 10,000 (36.2%)
3,630 / 10,000 (36.3%)
3,640 / 10,000 (36.4%)
3,650 / 10,000 (36.5%)
3,660 / 10,000 (36.6%)
3,670 / 10,000 (36.7%)
3,680 / 10,000 (36.8%)
3,690 / 10,000 (36.9%)
3,700 / 10,000 (37.0%)
3,710 / 10,000 (37.1%)
3,720 / 10,000 (37.2%)
3,730 / 10,000 (37.3%)
3,740 / 10,000 (37.4%)
3,750 / 10,000 (37.5%)
3,760 / 10,000 (37.6%)
3,770 / 10,000 (37.7%)
3,780 / 10,000 (37.8%)
3,790 / 10,000 (37.9%)
3,800 / 10,000 (38.0%)
3,810 / 10,000 (38.1%)
3,820 / 10,000 (38.2%)
3,830 / 10,000 (38.3%)
3,840 / 10,000 (38.4%)
3,850 / 10,000 (38.5%)
3,860 / 10,000 (38.6%)
3,870 / 10,000 (38.7%)
3,880 / 10,000 (38.8%)
3,890 / 10,000 (38.9%)
3,900 / 10,000 (39.0%)
3,910 / 10,000 (39.1%)
3,920 / 10,000 (39.2%)
3,930 / 10,000 (39.3%)
3,940 / 10,000 (39.4%)
3,950 / 10,000 (39.5%)
3,960 / 10,000 (39.6%)
3,970 / 10,000 (39.7%)
3,980 / 10,000 (39.8%)
3,990 / 10,000 (39.9%)
4,000 / 10,000 (40.0%)
4,010 / 10,000 (40.1%)
4,020 / 10,000 (40.2%)
4,030 / 10,000 (40.3%)
4,040 / 10,000 (40.4%)
4,050 / 10,000 (40.5%)
4,060 / 10,000 (40.6%)
4,070 / 10,000 (40.7%)
4,080 / 10,000 (40.8%)
4,090 / 10,000 (40.9%)
4,100 / 10,000 (41.0%)
4,110 / 10,000 (41.1%)
4,120 / 10,000 (41.2%)
4,130 / 10,000 (41.3%)
4,140 / 10,000 (41.4%)
4,150 / 10,000 (41.5%)
4,160 / 10,000 (41.6%)
4,170 / 10,000 (41.7%)
4,180 / 10,000 (41.8%)
4,190 / 10,000 (41.9%)
4,200 / 10,000 (42.0%)
4,210 / 10,000 (42.1%)
4,220 / 10,000 (42.2%)
4,230 / 10,000 (42.3%)
4,240 / 10,000 (42.4%)
4,250 / 10,000 (42.5%)
4,260 / 10,000 (42.6%)
4,270 / 10,000 (42.7%)
4,280 / 10,000 (42.8%)
4,290 / 10,000 (42.9%)
4,300 / 10,000 (43.0%)
4,310 / 10,000 (43.1%)
4,320 / 10,000 (43.2%)
4,330 / 10,000 (43.3%)
4,340 / 10,000 (43.4%)
4,350 / 10,000 (43.5%)
4,360 / 10,000 (43.6%)
4,370 / 10,000 (43.7%)
4,380 / 10,000 (43.8%)
4,390 / 10,000 (43.9%)
4,400 / 10,000 (44.0%)
4,410 / 10,000 (44.1%)
4,420 / 10,000 (44.2%)
4,430 / 10,000 (44.3%)
4,440 / 10,000 (44.4%)
4,450 / 10,000 (44.5%)
4,460 / 10,000 (44.6%)
4,470 / 10,000 (44.7%)
4,480 / 10,000 (44.8%)
4,490 / 10,000 (44.9%)
4,500 / 10,000 (45.0%)
4,510 / 10,000 (45.1%)
4,520 / 10,000 (45.2%)
4,530 / 10,000 (45.3%)
4,540 / 10,000 (45.4%)
4,550 / 10,000 (45.5%)
4,560 / 10,000 (45.6%)
4,570 / 10,000 (45.7%)
4,580 / 10,000 (45.8%)
4,590 / 10,000 (45.9%)
4,600 / 10,000 (46.0%)
4,610 / 10,000 (46.1%)
4,620 / 10,000 (46.2%)
4,630 / 10,000 (46.3%)
4,640 / 10,000 (46.4%)
4,650 / 10,000 (46.5%)
4,660 / 10,000 (46.6%)
4,670 / 10,000 (46.7%)
4,680 / 10,000 (46.8%)
4,690 / 10,000 (46.9%)
4,700 / 10,000 (47.0%)
4,710 / 10,000 (47.1%)
4,720 / 10,000 (47.2%)
4,730 / 10,000 (47.3%)
4,740 / 10,000 (47.4%)
4,750 / 10,000 (47.5%)
4,760 / 10,000 (47.6%)
4,770 / 10,000 (47.7%)
4,780 / 10,000 (47.8%)
4,790 / 10,000 (47.9%)
4,800 / 10,000 (48.0%)
4,810 / 10,000 (48.1%)
4,820 / 10,000 (48.2%)
4,830 / 10,000 (48.3%)
4,840 / 10,000 (48.4%)
4,850 / 10,000 (48.5%)
4,860 / 10,000 (48.6%)
4,870 / 10,000 (48.7%)
4,880 / 10,000 (48.8%)
4,890 / 10,000 (48.9%)
4,900 / 10,000 (49.0%)
4,910 / 10,000 (49.1%)
4,920 / 10,000 (49.2%)
4,930 / 10,000 (49.3%)
4,940 / 10,000 (49.4%)
4,950 / 10,000 (49.5%)
4,960 / 10,000 (49.6%)
4,970 / 10,000 (49.7%)
4,980 / 10,000 (49.8%)
4,990 / 10,000 (49.9%)
5,000 / 10,000 (50.0%)
5,010 / 10,000 (50.1%)
5,020 / 10,000 (50.2%)
5,030 / 10,000 (50.3%)
5,040 / 10,000 (50.4%)
5,050 / 10,000 (50.5%)
5,060 / 10,000 (50.6%)
5,070 / 10,000 (50.7%)
5,080 / 10,000 (50.8%)
5,090 / 10,000 (50.9%)
5,100 / 10,000 (51.0%)
5,110 / 10,000 (51.1%)
5,120 / 10,000 (51.2%)
5,130 / 10,000 (51.3%)
5,140 / 10,000 (51.4%)
5,150 / 10,000 (51.5%)
5,160 / 10,000 (51.6%)
5,170 / 10,000 (51.7%)
5,180 / 10,000 (51.8%)
5,190 / 10,000 (51.9%)
5,200 / 10,000 (52.0%)
5,210 / 10,000 (52.1%)
5,220 / 10,000 (52.2%)
5,230 / 10,000 (52.3%)
5,240 / 10,000 (52.4%)
5,250 / 10,000 (52.5%)
5,260 / 10,000 (52.6%)
5,270 / 10,000 (52.7%)
5,280 / 10,000 (52.8%)
5,290 / 10,000 (52.9%)
5,300 / 10,000 (53.0%)
5,310 / 10,000 (53.1%)
5,320 / 10,000 (53.2%)
5,330 / 10,000 (53.3%)
5,340 / 10,000 (53.4%)
5,350 / 10,000 (53.5%)
5,360 / 10,000 (53.6%)
5,370 / 10,000 (53.7%)
5,380 / 10,000 (53.8%)
5,390 / 10,000 (53.9%)
5,400 / 10,000 (54.0%)
5,410 / 10,000 (54.1%)
5,420 / 10,000 (54.2%)
5,430 / 10,000 (54.3%)
5,440 / 10,000 (54.4%)
5,450 / 10,000 (54.5%)
5,460 / 10,000 (54.6%)
5,470 / 10,000 (54.7%)
5,480 / 10,000 (54.8%)
5,490 / 10,000 (54.9%)
5,500 / 10,000 (55.0%)
5,510 / 10,000 (55.1%)
5,520 / 10,000 (55.2%)
5,530 / 10,000 (55.3%)
5,540 / 10,000 (55.4%)
5,550 / 10,000 (55.5%)
5,560 / 10,000 (55.6%)
5,570 / 10,000 (55.7%)
5,580 / 10,000 (55.8%)
5,590 / 10,000 (55.9%)
5,600 / 10,000 (56.0%)
5,610 / 10,000 (56.1%)
5,620 / 10,000 (56.2%)
5,630 / 10,000 (56.3%)
5,640 / 10,000 (56.4%)
5,650 / 10,000 (56.5%)
5,660 / 10,000 (56.6%)
5,670 / 10,000 (56.7%)
5,680 / 10,000 (56.8%)
5,690 / 10,000 (56.9%)
5,700 / 10,000 (57.0%)
5,710 / 10,000 (57.1%)
5,720 / 10,000 (57.2%)
5,730 / 10,000 (57.3%)
5,740 / 10,000 (57.4%)
5,750 / 10,000 (57.5%)
5,760 / 10,000 (57.6%)
5,770 / 10,000 (57.7%)
5,780 / 10,000 (57.8%)
5,790 / 10,000 (57.9%)
5,800 / 10,000 (58.0%)
5,810 / 10,000 (58.1%)
5,820 / 10,000 (58.2%)
5,830 / 10,000 (58.3%)
5,840 / 10,000 (58.4%)
5,850 / 10,000 (58.5%)
5,860 / 10,000 (58.6%)
5,870 / 10,000 (58.7%)
5,880 / 10,000 (58.8%)
5,890 / 10,000 (58.9%)
5,900 / 10,000 (59.0%)
5,910 / 10,000 (59.1%)
5,920 / 10,000 (59.2%)
5,930 / 10,000 (59.3%)
5,940 / 10,000 (59.4%)
5,950 / 10,000 (59.5%)
5,960 / 10,000 (59.6%)
5,970 / 10,000 (59.7%)
5,980 / 10,000 (59.8%)
5,990 / 10,000 (59.9%)
6,000 / 10,000 (60.0%)
6,010 / 10,000 (60.1%)
6,020 / 10,000 (60.2%)
6,030 / 10,000 (60.3%)
6,040 / 10,000 (60.4%)
6,050 / 10,000 (60.5%)
6,060 / 10,000 (60.6%)
6,070 / 10,000 (60.7%)
6,080 / 10,000 (60.8%)
6,090 / 10,000 (60.9%)
6,100 / 10,000 (61.0%)
6,110 / 10,000 (61.1%)
6,120 / 10,000 (61.2%)
6,130 / 10,000 (61.3%)
6,140 / 10,000 (61.4%)
6,150 / 10,000 (61.5%)
6,160 / 10,000 (61.6%)
6,170 / 10,000 (61.7%)
6,180 / 10,000 (61.8%)
6,190 / 10,000 (61.9%)
6,200 / 10,000 (62.0%)
6,210 / 10,000 (62.1%)
6,220 / 10,000 (62.2%)
6,230 / 10,000 (62.3%)
6,240 / 10,000 (62.4%)
6,250 / 10,000 (62.5%)
6,260 / 10,000 (62.6%)
6,270 / 10,000 (62.7%)
6,280 / 10,000 (62.8%)
6,290 / 10,000 (62.9%)
6,300 / 10,000 (63.0%)
6,310 / 10,000 (63.1%)
6,320 / 10,000 (63.2%)
6,330 / 10,000 (63.3%)
6,340 / 10,000 (63.4%)
6,350 / 10,000 (63.5%)
6,360 / 10,000 (63.6%)
6,370 / 10,000 (63.7%)
6,380 / 10,000 (63.8%)
6,390 / 10,000 (63.9%)
6,400 / 10,000 (64.0%)
6,410 / 10,000 (64.1%)
6,420 / 10,000 (64.2%)
6,430 / 10,000 (64.3%)
6,440 / 10,000 (64.4%)
6,450 / 10,000 (64.5%)
6,460 / 10,000 (64.6%)
6,470 / 10,000 (64.7%)
6,480 / 10,000 (64.8%)
6,490 / 10,000 (64.9%)
6,500 / 10,000 (65.0%)
6,510 / 10,000 (65.1%)
6,520 / 10,000 (65.2%)
6,530 / 10,000 (65.3%)
6,540 / 10,000 (65.4%)
6,550 / 10,000 (65.5%)
6,560 / 10,000 (65.6%)
6,570 / 10,000 (65.7%)
6,580 / 10,000 (65.8%)
6,590 / 10,000 (65.9%)
6,600 / 10,000 (66.0%)
6,610 / 10,000 (66.1%)
6,620 / 10,000 (66.2%)
6,630 / 10,000 (66.3%)
6,640 / 10,000 (66.4%)
6,650 / 10,000 (66.5%)
6,660 / 10,000 (66.6%)
6,670 / 10,000 (66.7%)
6,680 / 10,000 (66.8%)
6,690 / 10,000 (66.9%)
6,700 / 10,000 (67.0%)
6,710 / 10,000 (67.1%)
6,720 / 10,000 (67.2%)
6,730 / 10,000 (67.3%)
6,740 / 10,000 (67.4%)
6,750 / 10,000 (67.5%)
6,760 / 10,000 (67.6%)
6,770 / 10,000 (67.7%)
6,780 / 10,000 (67.8%)
6,790 / 10,000 (67.9%)
6,800 / 10,000 (68.0%)
6,810 / 10,000 (68.1%)
6,820 / 10,000 (68.2%)
6,830 / 10,000 (68.3%)
6,840 / 10,000 (68.4%)
6,850 / 10,000 (68.5%)
6,860 / 10,000 (68.6%)
6,870 / 10,000 (68.7%)
6,880 / 10,000 (68.8%)
6,890 / 10,000 (68.9%)
6,900 / 10,000 (69.0%)
6,910 / 10,000 (69.1%)
6,920 / 10,000 (69.2%)
6,930 / 10,000 (69.3%)
6,940 / 10,000 (69.4%)
6,950 / 10,000 (69.5%)
6,960 / 10,000 (69.6%)
6,970 / 10,000 (69.7%)
6,980 / 10,000 (69.8%)
6,990 / 10,000 (69.9%)
7,000 / 10,000 (70.0%)
7,010 / 10,000 (70.1%)
7,020 / 10,000 (70.2%)
7,030 / 10,000 (70.3%)
7,040 / 10,000 (70.4%)
7,050 / 10,000 (70.5%)
7,060 / 10,000 (70.6%)
7,070 / 10,000 (70.7%)
7,080 / 10,000 (70.8%)
7,090 / 10,000 (70.9%)
7,100 / 10,000 (71.0%)
7,110 / 10,000 (71.1%)
7,120 / 10,000 (71.2%)
7,130 / 10,000 (71.3%)
7,140 / 10,000 (71.4%)
7,150 / 10,000 (71.5%)
7,160 / 10,000 (71.6%)
7,170 / 10,000 (71.7%)
7,180 / 10,000 (71.8%)
7,190 / 10,000 (71.9%)
7,200 / 10,000 (72.0%)
7,210 / 10,000 (72.1%)
7,220 / 10,000 (72.2%)
7,230 / 10,000 (72.3%)
7,240 / 10,000 (72.4%)
7,250 / 10,000 (72.5%)
7,260 / 10,000 (72.6%)
7,270 / 10,000 (72.7%)
7,280 / 10,000 (72.8%)
7,290 / 10,000 (72.9%)
7,300 / 10,000 (73.0%)
7,310 / 10,000 (73.1%)
7,320 / 10,000 (73.2%)
7,330 / 10,000 (73.3%)
7,340 / 10,000 (73.4%)
7,350 / 10,000 (73.5%)
7,360 / 10,000 (73.6%)
7,370 / 10,000 (73.7%)
7,380 / 10,000 (73.8%)
7,390 / 10,000 (73.9%)
7,400 / 10,000 (74.0%)
7,410 / 10,000 (74.1%)
7,420 / 10,000 (74.2%)
7,430 / 10,000 (74.3%)
7,440 / 10,000 (74.4%)
7,450 / 10,000 (74.5%)
7,460 / 10,000 (74.6%)
7,470 / 10,000 (74.7%)
7,480 / 10,000 (74.8%)
7,490 / 10,000 (74.9%)
7,500 / 10,000 (75.0%)
7,510 / 10,000 (75.1%)
7,520 / 10,000 (75.2%)
7,530 / 10,000 (75.3%)
7,540 / 10,000 (75.4%)
7,550 / 10,000 (75.5%)
7,560 / 10,000 (75.6%)
7,570 / 10,000 (75.7%)
7,580 / 10,000 (75.8%)
7,590 / 10,000 (75.9%)
7,600 / 10,000 (76.0%)
7,610 / 10,000 (76.1%)
7,620 / 10,000 (76.2%)
7,630 / 10,000 (76.3%)
7,640 / 10,000 (76.4%)
7,650 / 10,000 (76.5%)
7,660 / 10,000 (76.6%)
7,670 / 10,000 (76.7%)
7,680 / 10,000 (76.8%)
7,690 / 10,000 (76.9%)
7,700 / 10,000 (77.0%)
7,710 / 10,000 (77.1%)
7,720 / 10,000 (77.2%)
7,730 / 10,000 (77.3%)
7,740 / 10,000 (77.4%)
7,750 / 10,000 (77.5%)
7,760 / 10,000 (77.6%)
7,770 / 10,000 (77.7%)
7,780 / 10,000 (77.8%)
7,790 / 10,000 (77.9%)
7,800 / 10,000 (78.0%)
7,810 / 10,000 (78.1%)
7,820 / 10,000 (78.2%)
7,830 / 10,000 (78.3%)
7,840 / 10,000 (78.4%)
7,850 / 10,000 (78.5%)
7,860 / 10,000 (78.6%)
7,870 / 10,000 (78.7%)
7,880 / 10,000 (78.8%)
7,890 / 10,000 (78.9%)
7,900 / 10,000 (79.0%)
7,910 / 10,000 (79.1%)
7,920 / 10,000 (79.2%)
7,930 / 10,000 (79.3%)
7,940 / 10,000 (79.4%)
7,950 / 10,000 (79.5%)
7,960 / 10,000 (79.6%)
7,970 / 10,000 (79.7%)
7,980 / 10,000 (79.8%)
7,990 / 10,000 (79.9%)
8,000 / 10,000 (80.0%)
8,010 / 10,000 (80.1%)
8,020 / 10,000 (80.2%)
8,030 / 10,000 (80.3%)
8,040 / 10,000 (80.4%)
8,050 / 10,000 (80.5%)
8,060 / 10,000 (80.6%)
8,070 / 10,000 (80.7%)
8,080 / 10,000 (80.8%)
8,090 / 10,000 (80.9%)
8,100 / 10,000 (81.0%)
8,110 / 10,000 (81.1%)
8,120 / 10,000 (81.2%)
8,130 / 10,000 (81.3%)
8,140 / 10,000 (81.4%)
8,150 / 10,000 (81.5%)
8,160 / 10,000 (81.6%)
8,170 / 10,000 (81.7%)
8,180 / 10,000 (81.8%)
8,190 / 10,000 (81.9%)
8,200 / 10,000 (82.0%)
8,210 / 10,000 (82.1%)
8,220 / 10,000 (82.2%)
8,230 / 10,000 (82.3%)
8,240 / 10,000 (82.4%)
8,250 / 10,000 (82.5%)
8,260 / 10,000 (82.6%)
8,270 / 10,000 (82.7%)
8,280 / 10,000 (82.8%)
8,290 / 10,000 (82.9%)
8,300 / 10,000 (83.0%)
8,310 / 10,000 (83.1%)
8,320 / 10,000 (83.2%)
8,330 / 10,000 (83.3%)
8,340 / 10,000 (83.4%)
8,350 / 10,000 (83.5%)
8,360 / 10,000 (83.6%)
8,370 / 10,000 (83.7%)
8,380 / 10,000 (83.8%)
8,390 / 10,000 (83.9%)
8,400 / 10,000 (84.0%)
8,410 / 10,000 (84.1%)
8,420 / 10,000 (84.2%)
8,430 / 10,000 (84.3%)
8,440 / 10,000 (84.4%)
8,450 / 10,000 (84.5%)
8,460 / 10,000 (84.6%)
8,470 / 10,000 (84.7%)
8,480 / 10,000 (84.8%)
8,490 / 10,000 (84.9%)
8,500 / 10,000 (85.0%)
8,510 / 10,000 (85.1%)
8,520 / 10,000 (85.2%)
8,530 / 10,000 (85.3%)
8,540 / 10,000 (85.4%)
8,550 / 10,000 (85.5%)
8,560 / 10,000 (85.6%)
8,570 / 10,000 (85.7%)
8,580 / 10,000 (85.8%)
8,590 / 10,000 (85.9%)
8,600 / 10,000 (86.0%)
8,610 / 10,000 (86.1%)
8,620 / 10,000 (86.2%)
8,630 / 10,000 (86.3%)
8,640 / 10,000 (86.4%)
8,650 / 10,000 (86.5%)
8,660 / 10,000 (86.6%)
8,670 / 10,000 (86.7%)
8,680 / 10,000 (86.8%)
8,690 / 10,000 (86.9%)
8,700 / 10,000 (87.0%)
8,710 / 10,000 (87.1%)
8,720 / 10,000 (87.2%)
8,730 / 10,000 (87.3%)
8,740 / 10,000 (87.4%)
8,750 / 10,000 (87.5%)
8,760 / 10,000 (87.6%)
8,770 / 10,000 (87.7%)

In [6]:
!gunzip -c analysis/trimmed/reads_trimmed.fastq.gz | \
    NanoFilt -q 10 -l 900 --maxlength 1700 | \
    gzip > analysis/trimmed/ERR14817851_filtered.fastq.gz

In [7]:
!zcat analysis/trimmed/reads_trimmed.fastq.gz | wc -l
!zcat analysis/trimmed/ERR14817851_filtered.fastq.gz | wc -l

471668
163792

# 5. Final quality control with NanoPlot

In [8]:
!mamba run -n nanopore_qc NanoPlot \
    --fastq analysis/trimmed/ERR14817851_filtered.fastq.gz \
    -o analysis/fastqc_posttrim \
    -t 3

# Download
from google.colab import files
files.download("./analysis/fastqc_posttrim/NanoPlot-report.html")

# Open Nanoplot report
from IPython.display import HTML
with open("./analysis/fastqc_posttrim/NanoPlot-report.html", "r") as f:
    html = f.read()
HTML(html)

# 6. Kraken2 database setup

In [9]:
# You still need to manually update the taxonomy databases before Krona can
# generate taxonomic reports.  The update script is ktUpdateTaxonomy.sh.
# The default location for storing taxonomic databases is
#/usr/local/envs/kraken_krona/opt/krona/taxonomy

!mamba run -n kraken_krona ktUpdateTaxonomy.sh

# Download Kraken2 taxonomy
!mamba run -n kraken_krona kraken2-build --download-library viral --db viral_DB --use-ftp

Fetching taxdump.tar.gz...
   Fetching checksum...
   Checksum for taxdump.tar.gz matches server.
Extracting taxonomy...

Cleaning up...

Finished.

In [10]:
# Taxonomic classification with Kraken2
!mamba run -n kraken_krona kraken2 \
    --db viral_DB \
    --report analysis/kraken/kraken_report.txt \
    analysis/trimmed/ERR14817851_filtered.fastq.gz \
    --gzip \
    --output analysis/kraken/kraken_output.txt \
    --threads 3 \
    --confidence 0.1

# Download
from google.colab import files
files.download("./analysis/kraken/kraken_output.txt")

from google.colab import files
files.download("./analysis/kraken/kraken_report.txt")

Loading database information... done.
40948 sequences (49.36 Mbp) processed in 6.555s (374.8 Kseq/m, 451.83 Mbp/m).
  38993 sequences classified (95.23%)
  1955 sequences unclassified (4.77%)

# 8. Interactive visualization with Krona

In [11]:
!cut -f2,3 analysis/kraken/kraken_output.txt > \
    analysis/krona/kraken_krona_input.txt

!mamba run -n kraken_krona ktImportTaxonomy \
    analysis/krona/kraken_krona_input.txt \
    -o analysis/krona/krona_report.html

# Download
from google.colab import files
files.download("./analysis/krona/krona_report.html")

Loading taxonomy...
Importing analysis/krona/kraken_krona_input.txt...
Writing analysis/krona/krona_report.html...

   [ WARNING ]  Too many query IDs to store in chart; storing supplemental
                files in 'analysis/krona/krona_report.html.files'.